export const users = [
  { id: 0, name: "John", age: 25, email: "john@example.com" },
  { id: 1, name: "Alice", age: 30, email: "alice@example.com" },
  { id: 2, name: "Bob", age: 28, email: "bob@example.com" },
  { id: 3, name: "Emily", age: 22, email: "emily@example.com" },
  { id: 4, name: "Michael", age: 35, email: "michael@example.com" },
  { id: 5, name: "Sarah", age: 27, email: "sarah@example.com" },
  { id: 6, name: "David", age: 32, email: "david@example.com" },
  { id: 7, name: "Olivia", age: 29, email: "olivia@example.com" },
  { id: 8, name: "Daniel", age: 31, email: "daniel@example.com" },
  { id: 9, name: "Emma", age: 26, email: "emma@example.com" },
  { id: 10, name: "James", age: 33, email: "james@example.com" },
  { id: 11, name: "Sophia", age: 24, email: "sophia@example.com" },
  { id: 12, name: "William", age: 27, email: "william@example.com" },
  { id: 13, name: "Ava", age: 29, email: "ava@example.com" },
  { id: 14, name: "Liam", age: 28, email: "liam@example.com" },
  { id: 15, name: "Mia", age: 31, email: "mia@example.com" },
  { id: 16, name: "Benjamin", age: 26, email: "benjamin@example.com" },
  { id: 17, name: "Ella", age: 30, email: "ella@example.com" },
  { id: 18, name: "Alexander", age: 23, email: "alexander@example.com" },
  { id: 19, name: "Grace", age: 32, email: "grace@example.com" },
];
